### ISSUE TITLE
Glitch with covington

### ISSUE THREAD

**Issue by jspitz** [amunn/movement-arrows#3]
Thanks for this package. It basically also seems to work with `covington`. However, glosses are broken by the `\glt` redefinition.

It seems the following is sufficient to make it work:
```tex
\AtBeginDocument{%
\ifdefined\eachwordone\preto{\eachwordone}{\MVA@arrowstrut}%
\@ifpackageloaded{covington}{}{\renewcommand\glt{\vskip -1.2\arrowheight}}%
\let\trans=\glt
\fi}
```

The extra vertical space after the first gloss line is always there, notwithstanding whether there is an arrow in the gloss or not. I don't know if this is intentional or also the case with the other glossing packages (haven't checked).

**Comment by amunn** [comment]
Thanks for the report. Since I don't use `covington` but I'm happy to support it, could you construct a sample document like the ones in the repo for the other example packages that I can play with? The extra space should disappear automatically in subsequent examples.

**Comment by jspitz** [comment]
Sure. Here is the example along the line of the ones included:
```tex
\documentclass{article}
\usepackage[margin=2in]{geometry}
\usepackage{covington}
\usepackage{movement-arrows}

\begin{document}

\begin{subexamples}
	\item\digloss
	    {\ldots dat Jan \mkword[een]{een auto} gisteren \mkword{t}  gekregen heeft.}
	    {\ldots that John {a \hspace*{1em} car}  yesterday t gotten has}
	    {\ldots that John a car yesterday.}
	    \arrow{t}{een}
	\item \mkword{Where} did this move from \mkword{t}?
	      \arrow[circ=1]{t}{Where}
	\item Another example.
\end{subexamples}

\begin{subexamples}
\item This \mkword{is} not \mkword[t]{<be>} verb movement.
	  \arrow{t}{is}
\item It  \mkword{PRES} not \mkword[be]{be} verb lowering.
	  \arrow[circ=2]{PRES}{be}
\end{subexamples}

\end{document}
```
output with my suggested fix:
![grafik](https://github.com/amunn/movement-arrows/assets/4538783/41e28610-008c-469c-8259-6ef3da6af15b)

Note the wrong output of <be> which I also get with the `linguex` example.

**Comment by jspitz** [comment]
> Note the wrong output of `<be>` which I also get with the `linguex` example.

Oh, that's just missing
```tex
\usepackage[T1]{fontenc}
```

I suppose this needs to be added to all examples.

**Comment by amunn** [comment]
Thanks for the comments. I realize now that some of the problems I solved in the earlier version of the package disappeared in my rush to put out the new version. You're right that there needs to be a way to indicate a gloss line with an arrow; I had that functionality before in the form of an `\arrowex` macro and clearly shouldn't have taken it out. I'd like to avoid manual intervention as much as possible though.

**Comment by jspitz** [comment]
I am not sure it can be done without any manual intervention (without changing the way glosses are constructed in the various packages). I think the proposed switches are convenient enough for the purpose. An alternative would be a one-time hook (à la `biblatex'`s `\AtNext...`)

**Comment by amunn** [comment]
Yes, I agree. Looking back at my original solution, I think a single command issued before the gloss line should be sufficient though. Currently testing that. Thanks a lot for the discussion and suggestions.

**Comment by amunn** [comment]
Fixed with the new version. `\arrow` command name has now been renamed `\mvarrow` to avoid package conflicts.
